spring:
  dubbo:
    application:
      name: consumer
#spring.dubbo.registry.address=zookeeper://119.23.59.213:2182
    registry:
      address:  multicast://224.5.6.7:1234?unicast=false
    scan: com.lantaiyuan.microservice.svca
    module:
      name: test